if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("AnnotationDbi", "annotate", "biomaRt"))
BiocManager::install("org.Hs.eg.db")
BiocManager::install("methylKit")
BiocManager::install("edgeR")
BiocManager::install("DESeq2")
BiocManager::install("genomation")
install.packages("tidyverse", repos = "http://cran.us.r-project.org")
install.packages("readr", repos = "http://cran.us.r-project.org")